<a href="https://colab.research.google.com/github/karywnl/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy - Numerical Python**

NumPy's ndarray is a fast, ***homogeneous*** multidimensional array. The power is in ***vectorized computation*** doing math on entire arrays without Python loops, which is orders of magnitude faster for large data.


In [2]:
import numpy as np

In [3]:
data = np.array([[1, 3, 0.5],
                        [9, 10, 3]])
data

array([[ 1. ,  3. ,  0.5],
       [ 9. , 10. ,  3. ]])

In [4]:
data.dtype

dtype('float64')

Note : Most common datatype of choice in numpy array is float64. Just because it is saver and operations such as division always return float.

In [5]:
type(data)

numpy.ndarray

There are multiple ways to create an narray as well.

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])