<a href="https://colab.research.google.com/github/karywnl/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy - Numerical Python**

NumPy's ndarray is a fast, ***homogeneous*** multidimensional array. The power is in ***vectorized computation*** doing math on entire arrays without Python loops, which is orders of magnitude faster for large data.


In [ ]:
import numpy as np

In [ ]:
data = np.array([[1, 3, 0.5],
                        [9, 10, 3]])
data

array([[ 1. ,  3. ,  0.5],
       [ 9. , 10. ,  3. ]])

In [ ]:
data.dtype

dtype('float64')

Note : Most common datatype of choice in numpy array is float64. Just because it is saver and operations such as division always return float.

In [ ]:
type(data)

numpy.ndarray

There are multiple ways to create an narray as well.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

Note : Same could be done with np.ones()

We can also create an array with our own datatype., by intializing the dtype while intialization.

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.int64)

Also we can convert a particular array using .astype()

In [ ]:
arr1.astype(np.bytes_)

array([b'1', b'2', b'3'], dtype='|S21')

***Note : Arithmetic and other indexing operations works exactly like normal python.***

Arithmetic operations here are vectorized means you don't have to write loops to do the operations.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
arr1 + arr2

array([5, 7, 9])

In [ ]:
arr1 - arr2

array([-3, -3, -3])

In [ ]:
arr1 * arr2

array([ 4, 10, 18])

In [ ]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [ ]:
arr1 ** 2

array([1, 4, 9])

They go hand in hand with the corresponding element. Think of the array as an vector - You will get the idea.

Also, there is comparision operators that yield us boolean values.

In [ ]:
arr1 > 1

array([False,  True,  True])

***Broadcasting*** : NumPy arrays have a concept of broadcasting. That allows them to multiply to different arrays with different shapes.

In [ ]:
barr1 = np.array([2])
barr2 = np.array([10, 20, 30])

barr1 * barr2

array([20, 40, 60])

Normally for this to happen we need to create copies to match the dimension of the extented one.

For eg : we copy the element 2 in barr, 3 times to essentially create [2, 2, 2] inorder to match the dimension of the barr2 and then do the multiplication. This requires new memory and it is inefficient.

Broadcasting doesn't use extra memory - It just broadcasts the element when required by calculating strides.

strides : how many bytes to jump to the next element.

In [ ]:
row = np.array([10, 20, 30])
print(row.strides)        # (8,) — 8 bytes per element

# Broadcast it to (3,3) explicitly using as_strided or broadcast_to
expanded = np.broadcast_to(row, (3, 3))
print(expanded.strides)   # (0, 8) — 0 bytes to move to next row!
print(expanded)
# [[10, 20, 30],
#  [10, 20, 30],
#  [10, 20, 30]]

(8,)
(0, 8)
[[10 20 30]
 [10 20 30]
 [10 20 30]]


This exactly how the numpy array expand to match the dimension and no extra memory.

Idea is instead of copying the element and put it in a new memory, we just point to same memory again and again, essentially broadcasting it.

In [ ]:
#Outer Product
col_vect = np.array([[1], [2], [3]])   # shape (3, 1)
row_vect = np.array([10, 20, 30])      # shape (1, 3) — 1D treated as (1,3)
col_vect + row_vect

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

Thus, normally to do (3, 1) * (1, 3) - What we do we create them both are (3,3) and then add them. But Now we are just brodcasting.

**Indexing and Slicing**

Indexing and Slicing of numpy arrays work exactly like python list. Still, there are some differences.

Distinction between list and numpy array is seen while slicing and putting it in another variable.

In [ ]:
python_lst = [0, 1, 2, 3, 4]
chunk = python_lst[2:4]   # brand new list, independent copy
chunk[0] = 99
print(python_lst)         # [0, 1, 2, 3, 4] — unchanged!

[0, 1, 2, 3, 4]


In [ ]:
numpy_arr = np.arange(5)
chunk = numpy_arr[2:4]   # view into same memory
chunk[0] = 99
print(numpy_arr)         # [0, 1, 99, 3, 4] — original changed!

[ 0  1 99  3  4]


***Python list slices are always a copy***

***NumPy array slices are always a view***

If you need to create numpy array slice as a copy, you can do that by doing arr[i:j].copy()

***Boolean Indexing***

In [ ]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
#Normal Indexing arr[row, col]
# arr[ row_start : row_end, col_start : col_end ]
data[:, :]

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [ ]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

Here, Only the ones with the True value are displaying. Here, we are doing boolean indexing on rows.

In [ ]:
data[names == "Bob", 1: ]         #boolean indexing on rows and for columns 1: end (i.e.) just 1

array([[7],
       [0]])

In [ ]:
data[names == "Bob", 1]

array([7, 0])

Both of the above too are identical, The way we index differs, using coln (:) yields us with seperated rows - Because what if there is another column like now there are 3 columns indexed as 0, 1, 2 and we are doing [1:] so 1 is the start and 2 is the end and 2 is not included, Thus giving us only 1. But it would be a 2D array

On the other hand we explicitly told that we nee only one column and that is 1. So, row index is boolean index and column is only 1. So, Thus it gets returned as a 1D array.